<a href="https://colab.research.google.com/github/srija2771/pytorch/blob/main/pytorch/00_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


In [ ]:
## Introduction to Tensor
###creating sensors

In [ ]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#get tensor back as python int
 scalar.item()

7

In [ ]:
#vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#matrix
MATRIX=torch.tensor([[7,8],
                    [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
#tensor
TENSOR=torch.tensor([[[1,2,3],
                      [3,6,9],
                      [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [23]:
#create a random tensor of size (3,4)
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.8711, 0.5746, 0.8013, 0.1541],
        [0.4087, 0.9738, 0.4989, 0.5799],
        [0.4677, 0.0819, 0.5046, 0.5554]])

In [24]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor=torch.rand(size=(224,224,3))
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [26]:
#create a tensor of all zeros
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
#create atensor of all ones
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [29]:
ones.dtype

torch.float32

In [30]:
random_tensor.dtype

torch.float32

In [34]:
#use torch.range()
a=torch.arange(start=1,end=11,step=1)
a

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
#creating a tensors like
ten_zeros=torch.zeros_like(input=a)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])